project:
  type: website
  output-dir: docs

website:
  title: "caitraz.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: About
      - href: CV.qmd
        text: CV
      - href: Projects.qmd
        text: Projects


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

