---
title: "CV"
author: "Caitlin Rasbid"
---

# **Caitlin Rasbid**

### **HUMAN-ENVIRONMENT INTERACTION \| SUSTAINABLE RESOURCE USE \| ENVIRONMENTAL JUSTICE**

Hard-working individual with a passion for education on pressing issues of sustainability. With a double major in **Ecosystem Science and Sustainability** and **Environmental Sociology**, my professional focus lies on the human dynamics in natural resources, with a specific interest in sustainable resource use and the pursuit of environmental justice. I seek to apply my strengths in problem solving, communication, and attentiveness to a like-minded project.

## **Education**

### **Colorado State University, Fort Collins, CO** 

#### Expected graduation: May 2026

Double Major in Ecosystem Science and Sustainability & Environmental Sociology. Enrolled in the Honors Program.

## **Job Experience**

### **Alley Cat Cafe /** Barista

January 2024 - Present \| Fort Collins, CO

-Assisted customers in drink selection from an extensive menu of coffee, tea, and more, and rendered payment. 

-Prepared drinks customized to customer preference, including flavors, pulling espresso shots, frothing milk, and using the blender as needed.

-Maintained a clean workspace and shop environment.

### **All Creatures Animal Hospital /** Customer Service Representative

May 2020 - July 2022 \| Lake Zurich, IL

-Answered incoming phone calls and responded to client inquiries

-Greeted clients, performed client check-ins and end of appointment check-outs, and registered payment for appointments

-Assessed patient concerns and determined the level of emergency of a situation

-Mediated critical communications between clients and doctors

\

## **Sustainable Human-Environment Interaction Coursework**

**Honors Ecology** - Explored interrelationships among organisms and their environments using conceptual models and quantitative approaches. Researched and presented on challenges in natural resource management in the field of ecology. 

**Honors Sustainability Science -** Developed critical thinking across disciplines to explore solutions to improve human-social-ecological relationships and worked on a small group in writing up a class-wide sustainable research project. 

**Environment, Food, and Social Justice -** Critically analyzed the connection between social systems and inequalities in relation to food and the environment. 

**Environmental Justice** **-** Explored the structural forces leading to environmental disparities and how environmental activists and communities advocate for change.

\

## **Skills**

Ability to work under high pressure, time-sensitive environments; Fast learner; Attention to detail; Compassion for others; Proficient in Excel; experience in Animal care;

\

## **Accomplishments and Certifications**

International Review Board Certification (2024). Member of Xi Sigma Pi or Natural Resources Honors Society (as of Spring 2025)
